direction: down

CheckContext: |
  Check context for
  'iwpr' retrofit
shape: rectangle

IsInfoAvailable: |
  Is 'iwpr' info
  available?
shape: diamond

InfoNotAvailable: |
  Info for 'iwpr'
  not available
shape: rectangle

AvailableProcesses: |
  Context describes:
  REPT, IDoc
shape: rectangle

RequestDoc: |
  Request relevant
  documentation
shape: rectangle

CheckContext -> IsInfoAvailable
IsInfoAvailable -> InfoNotAvailable: No
InfoNotAvailable -> AvailableProcesses
AvailableProcesses -> RequestDoc